# Generated by Django 5.0.4 on 2024-04-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cashback_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_notification_required',
            field=models.BooleanField(default=True),
        ),
    ]
