# Generated by Django 4.2.11 on 2024-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
