# Generated by Django 5.0.4 on 2024-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_notif_sent',
            field=models.BooleanField(default=False),
        ),
    ]
